### ISSUE TITLE
Expand notification capabilities to a friend request

### ISSUE THREAD

**Issue by JuanCaicedo119** [GRarer/boop#59]
User should be able to receive a notification indicating someone sent them a friend's request.

**Comment by grarer** [comment]
here are the parts of the code you'll want to look at:

`friendsRouter.ts` contains the handler for requesting to send a friend request. see the section that starts with `friendsRouter.post('/send_request'`. at the end of this handler is where we should send the notification. if you also want to send a notification when someone accepts a friend request, that's also in this file in the handler starting with `friendsRouter.post('/answer_request',`

`pushQueries.ts` contains the `getPushByUUID` function, which will query the database and get you the array of web-push VAPID subscriptions for a given user. to send a notification, you'll need to pass that array of subscriptions to the `sendNotificationToUser` function in `pushManager.ts`.

the other parameter of sendNotificationToUser is an object that provides the content of the message. `boopNotificationPayload` in `reminders.ts` is a good example of how this should work; you'll want to make a new version of that with different title, body, and action. you don't need to include the `data` field of the notification for this one since we don't need to pass any extra information into the service worker.

assuming that you include an action (which creates a clickable button on the notification that should open the app), you'll need to modify the notification click handler in `boopServiceWorker.js` to respond to your new action by opening the `add_friends` page.
