### ISSUE TITLE
Contact Methods

### ISSUE THREAD

**Issue by grarer** [GRarer/boop#8]
Users should provide 1 or more forms of contact: phone numbers or usernames for social messaging platforms like Discord, WhatsApp, Messenger, etc. They should be prompted to add at least 1 method when they sign up, and they should be able to edit, remove, or add methods later.

One thing we need to figure out is what format to use for this information. Should we have a list of supported chat platforms, or allow users to enter whatever they want? How do we support users listing two usernames for the same platform?

**Comment by jelloshots13** [comment]
1. As a user, I want to display my contact info, so that my Boop friends are able to "Boop me" (communicate with me) through platforms that I prefer.
2. As a user, I want to display my contact info in order of preference, so that my Boop friends are able to see which platforms I like to communicate with the most.
3. As a user, I want to be able to add/edit/remove individual contact info, so that I can keep my Contact Info page up to date and make it easier for my Boop friends to get in contact with me.
4. As a user, I want to be able to display contact info on lesser known platforms, so that my Boop friends can have as many avenues of communication with me as I prefer.
5. As a user, I want to visually comprehend which contact info cards are links (to the respective platform) and which contact info cards aren't, so that I can communicate with my Boop friends efficiently.

***NOTE***
-My Contact Info page will be what is displayed to other users upon them receiving a notification to Boop me.
-Contact Info page is separate, but connected to my Profile page. Profile page will probably display the top 2-3 contact methods, but not all of them; however, users have the ability to display all contact methods.

**Comment by grarer** [comment]
I'm attaching  the design sketches that Jiale made for this feature so that they are included in the paper trail for this issue. He designed a really clean card-based UI for editing contact details.

![image.png](https://images.zenhubusercontent.com/6001cbcba531f869637be41a/97374c95-f041-407d-9fa4-c19ec70cb681)

**Comment by grarer** [comment]
I should note that this issue and PR #27 only covers allowing a user to view and edit their own contact details. There will be a separate screen to view a friend's contact methods and start a chat, which is planned as a sprint 3 feature since that page will be triggered by the push notifications.
